name: Package

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check versions match
        run: ./s/check-version
